### ISSUE TITLE
Installer: aw_nav zeigt nach Update auf 0.3 weiter 0.21 als aktuelle Version an.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/aw_navigation#1]
Da wurde vermutlich irgendwo die Versionsnummer noch nicht ausgetauscht.

**Comment by AWqxKAWERbXo** [comment]
_push_

**Comment by AWqxKAWERbXo** [comment]
@gharlan kannst du das evtl. im Installer korrigieren?

**Comment by gharlan** [comment]
https://github.com/FriendsOfREDAXO/aw_navigation/blob/master/package.yml#L2

Hier steht doch auch noch 0.2.1

**Comment by AWqxKAWERbXo** [comment]
Im Installer wird, wenn man die aw_navigation installiert, ein Update auf 0.3 vorgeschlagen, obwohl beim Update letztlich wieder 0.2.1 installiert wird. Entweder, in der package.yml müsste 0.3 stehen, oder im Addon-Bereich 0.2.1, schätze ich. (Hab noch nie ein Addon hochgeladen)

**Comment by gharlan** [comment]
Ja, die Versionen müssen übereinstimmen. Wenn man über den Installer hochlädt, wird das erzwungen, beim Upload über redaxo.org aber nicht.
(Zukünftig soll redaxo.org die package.yml auslesen und sich da die nötigen Infos rausholen..)

**Comment by dtpop** [comment]
Ist korrigiert
