### ISSUE TITLE
aw_navigation taucht im Redaxo-Addons-Menü auf, obwohl Benutzer/Rolle dies nicht soll.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/aw_navigation#2]
In der Benutzerverwaltung ist die aw_navigation nicht explizit in einer Rolle freigegeben, trotzdem wird sie im Menü unter "Addons" gelistet.

**Comment by dtpop** [comment]
Das Addon wird nicht mehr im Menü angezeigt. Danke für den Hinweis!
